# Generated by Django 2.1.5 on 2020-06-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
    ]
