# Generated by Django 2.1.5 on 2020-06-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_data', '0002_auto_20200620_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
